server:
  port: 8081
spring:
  application:
    name: healthy-computer
dubbo:
  registry:
    address: zookeeper://101.34.31.13:2181
    timeout: 60000
  protocol:
    name: dubbo
  scan:
    base-packages: cn.aixan.controller